# While Cirrus CI gives open-source projects free 16.0 CPUs,
# we use only 2 CPUs x 3 tasks = 6 CPUs since the tests here aren't fully
# utilizing multiple CPUs.
# https://cirrus-ci.org/faq/#are-there-any-limits
#
# Undocumented constraints;
# - The maximum memory limit is 4G times the number of CPUs.
# - The number of CPUs should be multiple of 2.

task:
  name: FreeBSD
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    image: family/freebsd-13-1
    platform: freebsd
    cpu: 2
    memory: 8G
  go_modules_cache:
    folder: .gomodcache
    fingerprint_script: cat go.mod go.sum
  setup_script:
    - pkg install -y git-lite go golangci-lint gmake
    - go env -w GOMODCACHE=$(pwd)/.gomodcache
    - go mod download
    - env
    - which tar
    - tar --version
    - mount #ufs?
  build_script:
    - #gmake
    - true
  test_script:
    - gmake test
